import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Sparkles, ArrowLeft, ArrowRight, Check, Loader2, Plus, Pencil, Trash2, Globe2, Plug, Play } from 'lucide-react';
import api from '../../../api';
import {
  ExternalApiCallsEditor, ExternalApiFieldMappingsEditor,
  type ExternalApiCall, type ExternalApiFieldMappings, type FieldMappingRequest,
} from './ExternalApiCallsEditor';
import {
  McpServerConnectionEditor, McpToolPicker, McpToolCallsEditor, McpResponseMappingsEditor,
  type McpCall, type McpAuth, type McpResponseMapping,
} from './McpToolCallsEditor';
import { WorkflowFieldSuggestions, type WorkflowFieldSuggestion } from './WorkflowFieldSuggestions';
import { TestActionModal, type AutoMapProposal, type TestResult } from './TestActionModal';
import { AiAgentAdjustPanel, type AiAgentAdjustProposal } from './AiAgentAdjustPanel';
import { buildPreviewVars, substituteForPreview } from './apiCallPreview';
import './WorkflowDesignerModal.css';
import './ActionItemLibraryPage.css';
import './AiWorkflowBuilderPage.css';

type TargetType = 'external_api' | 'mcp_tool';

interface LibraryEntry {
  id: number;
  name: string;
  type: string;
  typeConfig: Record<string, unknown> | null;
  source: string;
  status: string;
}

type Mode = 'list' | 'wizard';

// external_api: 1 Documentation -> 2 Select Endpoint -> 3 Field Mapping -> 4 Test -> 5 Response
// Mapping -> 6 Review & Save. mcp_tool keeps its own unchanged sequence: 1 Describe & Paste -> 3
// Test & Map -> 4 Review & Save (steps 2/5/6 never used by that branch). One continuing AI session
// (sessionType "api_action_builder") spans every AI call across the whole external_api visit.
type Step = 1 | 2 | 3 | 4 | 5 | 6;

interface DiscoveredEndpoint {
  id: string;
  method: ExternalApiCall['method'];
  title: string;
  summary: string;
  recommended?: boolean;
  docExcerpt: string;
}

interface RequiredInput {
  placeholder: string;
  description: string;
  required: boolean;
  example?: string;
}

const MCP_STEP_BAR: { n: Step; key: string; def: string }[] = [
  { n: 1, key: 'awb_step_describe', def: 'Describe & Paste' },
  { n: 3, key: 'awb_step_test_map', def: 'Test & Map' },
  { n: 4, key: 'awb_step_review_save', def: 'Review & Save' },
];
const EXTERNAL_API_STEP_BAR: { n: Step; key: string; def: string }[] = [
  { n: 1, key: 'awb_step_documentation', def: 'Documentation' },
  { n: 2, key: 'awb_step_select_endpoint', def: 'Select Endpoint' },
  { n: 3, key: 'awb_step_field_mapping', def: 'Field Mapping' },
  { n: 4, key: 'awb_step_test', def: 'Test' },
  { n: 5, key: 'awb_step_response_mapping', def: 'Response Mapping' },
  { n: 6, key: 'awb_step_review_save', def: 'Review & Save' },
];

const TYPE_ICON: Record<string, React.ReactNode> = {
  external_api: <Globe2 size={16} />,
  mcp_tool: <Plug size={16} />,
};

const emptyMappings: ExternalApiFieldMappings = { request: [], response: [] };

// Merges an AutoMapProposal's per-call responseCaptures back into a draft's calls array, matched
// by the call's real id (never regenerated by the refine endpoint) — a call the proposal didn't
// address (e.g. its rawResponse was empty) is left completely untouched.
function mergeCapturesById<T extends { id: string; responseCaptures: any[] }>(
  calls: T[], proposalCalls: AutoMapProposal['calls'],
): T[] {
  return calls.map(c => {
    const p = proposalCalls.find(pc => pc.id === c.id);
    return p ? { ...c, responseCaptures: p.responseCaptures } : c;
  });
}

// Infers which wizard step a saved (possibly draft) library entry should resume into, purely from
// the shape of its typeConfig — no separate "step" column needed on the entity.
function inferResumeStep(entry: LibraryEntry): Step {
  const cfg = entry.typeConfig as any;
  const calls: any[] = cfg?.calls ?? [];
  if (calls.length === 0) {
    if (entry.type === 'mcp_tool') return 1;
    // Auto-saved after Step 1 (Discover Endpoints) but before a call was ever drafted — resume
    // straight at Select Endpoint instead of dumping the admin back at Documentation.
    const discovered = cfg?.aiWizard?.discoveredEndpoints ?? [];
    return discovered.length > 0 ? 2 : 1;
  }
  const hasResponseMapping =
    (cfg?.fieldMappings?.response?.length ?? 0) > 0 ||
    calls.some((c: any) => (c.responseCaptures?.length ?? 0) > 0);
  if (entry.type === 'mcp_tool') return hasResponseMapping ? 4 : 3;
  if (hasResponseMapping) return 6;
  const hasRequestMapping = (cfg?.fieldMappings?.request?.length ?? 0) > 0;
  return hasRequestMapping ? 4 : 3;
}

const bareFieldKey = (ticketField: string): string =>
  ticketField.startsWith('ticket.') ? ticketField.slice('ticket.'.length)
    : ticketField.startsWith('this.') ? ticketField.slice('this.'.length)
    : ticketField;

// Keeps a call's urlTemplate/bodyTemplate in sync with its request mapping table — a bug found
// live: adding a mapping row was pure bookkeeping (a placeholder name + a ticket field) with zero
// effect on the actual call, since {{placeholder}} only ever gets substituted if it's literally
// present in the template text already. These are text-based/best-effort (the templates are
// hand-edited strings, not a real parsed URL/JSON structure — same "not a real parser" spirit as
// ExternalApiActionExecutor's own regex-based substitution).
const placeholderRe = (placeholder: string) => new RegExp(`\\{\\{\\s*${placeholder.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*\\}\\}`);

function placeholderExistsInCall(call: ExternalApiCall, placeholder: string): boolean {
  const re = placeholderRe(placeholder);
  return re.test(call.urlTemplate) || re.test(call.bodyTemplate || '') || call.headers.some(h => re.test(h.valueTemplate));
}

// Appends a new query-string parameter ("&key={{placeholder}}") to the URL, unless the call has a
// non-empty JSON bodyTemplate and a method that actually sends one — then inserts a new field into
// the body object instead.
function addPlaceholderToCall(call: ExternalApiCall, placeholder: string): ExternalApiCall {
  const sendsBody = call.method !== 'GET' && call.method !== 'DELETE' && call.bodyTemplate.trim().length > 0;
  if (sendsBody) {
    const body = call.bodyTemplate.trim();
    if (body.startsWith('{') && body.endsWith('}')) {
      const inner = body.slice(1, -1).trim();
      const newField = `"${placeholder}": "{{${placeholder}}}"`;
      return { ...call, bodyTemplate: inner ? `{${inner}, ${newField}}` : `{${newField}}` };
    }
  }
  const separator = call.urlTemplate.includes('?') ? '&' : '?';
  return { ...call, urlTemplate: `${call.urlTemplate}${separator}${placeholder}={{${placeholder}}}` };
}

// Strips a placeholder's occurrence back out — the query-string segment that carries it, or the
// JSON body field, whichever is present.
function removePlaceholderFromCall(call: ExternalApiCall, placeholder: string): ExternalApiCall {
  const escaped = placeholder.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const urlTemplate = call.urlTemplate
    .replace(new RegExp(`[?&][^&=?]+=\\{\\{\\s*${escaped}\\s*\\}\\}`), '')
    .replace('?&', '?');
  const bodyTemplate = (call.bodyTemplate || '').replace(
    new RegExp(`,?\\s*"[^"]+"\\s*:\\s*"\\{\\{\\s*${escaped}\\s*\\}\\}"`), '');
  return { ...call, urlTemplate, bodyTemplate };
}

export const AiWorkflowBuilderPage = () => {
  const { t } = useTranslation();
  const [mode, setMode] = useState<Mode>('list');
  const [step, setStep] = useState<Step>(1);
  // Which Step 5 "Captured response" row (by index) is showing its full text instead of the
  // compact 140px scroll box — same fix as TestActionModal's expand toggle, for the same reason:
  // a real API response is often much longer than fits comfortably in that box.
  const [expandedResponseIndex, setExpandedResponseIndex] = useState<number | null>(null);
  // True when the wizard was reached by picking an existing entry from the list (draft or
  // complete) rather than by starting fresh — changes what the earliest reachable step's Back
  // button returns to.
  const [cameFromList, setCameFromList] = useState(false);

  // The global ticket field catalog (cross-template, not scoped to any one template)
  const [ticketFieldKeys, setTicketFieldKeys] = useState<string[]>([]);
  const [ticketFieldCatalog, setTicketFieldCatalog] = useState<{ fieldKey: string; fieldType: string }[]>([]);
  // Custom Workflow Fields (from Workflow Fields Manager) — used for "this.<key>" input/output
  const [workflowFieldKeys, setWorkflowFieldKeys] = useState<string[]>([]);
  const [workflowFieldCatalog, setWorkflowFieldCatalog] = useState<{ fieldKey: string; fieldType: string }[]>([]);
  // AI-suggested workflow fields with no existing match — see WorkflowFieldSuggestions.tsx.
  const [missingWorkflowFields, setMissingWorkflowFields] = useState<WorkflowFieldSuggestion[]>([]);
  const [libraryEntries, setLibraryEntries] = useState<LibraryEntry[]>([]);
  const [intent, setIntent] = useState('');
  const [documentation, setDocumentation] = useState('');
  const [generating, setGenerating] = useState(false);
  const [genError, setGenError] = useState('');
  const [actionType, setActionType] = useState<TargetType>('external_api');

  // Step 1 — MCP-specific (unchanged)
  const [mcpServerUrl, setMcpServerUrl] = useState('');
  const [mcpAuth, setMcpAuth] = useState<McpAuth>({ type: 'none' });
  const [mcpDiscoveredTools, setMcpDiscoveredTools] = useState<any[]>([]);

  // Persisted "api_action_builder" AiChatSession id — null until the first AI call of this wizard
  // visit; every later AI call across every step (discover/skeleton/map-fields/agent-adjust/
  // response-mapping) echoes it back so the AI remembers the whole conversation. external_api
  // only — mcp_tool never sends one, that flow is unchanged.
  const [wizardSessionId, setWizardSessionId] = useState<number | null>(null);

  // Step 1 (external_api) — fetch documentation from a URL instead of pasting it by hand
  const [documentationUrl, setDocumentationUrl] = useState('');
  const [fetchingDoc, setFetchingDoc] = useState(false);
  const [fetchDocError, setFetchDocError] = useState('');

  // Step 1 (external_api) — Discover Endpoints with AI
  const [discovering, setDiscovering] = useState(false);
  const [discoverError, setDiscoverError] = useState('');
  const [discoveredEndpoints, setDiscoveredEndpoints] = useState<DiscoveredEndpoint[]>([]);

  // Step 2 (external_api) — Select Endpoint / draft its call skeleton
  const [selectedEndpointId, setSelectedEndpointId] = useState<string | null>(null);
  const [skeletonLoading, setSkeletonLoading] = useState(false);
  const [skeletonError, setSkeletonError] = useState('');
  const [requiredInputs, setRequiredInputs] = useState<RequiredInput[]>([]);
  // Which draftCalls entry the guided flow built — the guided AI steps are scoped to exactly one
  // call; a second call can still be added manually via ExternalApiCallsEditor's "+ Add call".
  const [activeCallId, setActiveCallId] = useState<string | null>(null);

  // Step 3 (external_api) — Field Mapping + live preview
  const [mappingLoading, setMappingLoading] = useState(false);
  const [mappingError, setMappingError] = useState('');
  const [previewSampleValues, setPreviewSampleValues] = useState<Record<string, string>>({});

  // Step 4 (external_api) — the real test result, bubbled up from TestActionModal so Step 5 can
  // ground its response-mapping proposal in it without re-running the (possibly non-idempotent)
  // live call a second time.
  const [lastTestResult, setLastTestResult] = useState<TestResult | null>(null);
  // Lifted out of TestActionModal so it survives Back/Continue — that component gets
  // conditionally rendered per step, so an admin's typed sample values used to vanish every time
  // they navigated away from the Test step and back (a real bug found live).
  const [testSampleValues, setTestSampleValues] = useState<Record<string, string>>({});

  // Step 5 (external_api) — Response Mapping
  const [mappingResponseLoading, setMappingResponseLoading] = useState(false);
  const [mappingResponseError, setMappingResponseError] = useState('');
  const [responseMapProposal, setResponseMapProposal] = useState<AutoMapProposal | null>(null);
  // "Verify Captures" — re-checks JsonPaths against Step 4's already-fetched response instead of
  // re-invoking the (possibly non-idempotent) live API a second time just to confirm they resolve.
  const [verifyingCaptures, setVerifyingCaptures] = useState(false);
  const [verifyCapturesError, setVerifyCapturesError] = useState('');
  const [verifiedCapturedValues, setVerifiedCapturedValues] = useState<Record<string, unknown> | null>(null);

  // The draft itself
  const [nodeTitle, setNodeTitle] = useState('');
  const [draftCalls, setDraftCalls] = useState<ExternalApiCall[]>([]);
  const [draftMappings, setDraftMappings] = useState<ExternalApiFieldMappings>(emptyMappings);
  const [mcpDraftCalls, setMcpDraftCalls] = useState<McpCall[]>([]);
  const [mcpDraftMappings, setMcpDraftMappings] = useState<McpResponseMapping[]>([]);
  // Gates the final Continue into Review & Save — only true once a response mapping has actually
  // been applied (mcp: handleApplyAutoMap; external_api: applyResponseMapProposal).
  const [responseMapped, setResponseMapped] = useState(false);
  const [targetMode, setTargetMode] = useState<'new' | 'existing'>('new');
  const [targetNodeId, setTargetNodeId] = useState<string>('');
  const [saving, setSaving] = useState(false);
  const [savingDraft, setSavingDraft] = useState(false);
  const [saveError, setSaveError] = useState('');

  const reloadWorkflowFields = () =>
    api.get('/field-definitions', { params: { entityType: 'workflow' } })
      .then(r => {
        const custom = r.data.filter((f: any) => !f.isSystem);
        setWorkflowFieldKeys(custom.map((f: any) => f.fieldKey));
        setWorkflowFieldCatalog(custom.map((f: any) => ({ fieldKey: f.fieldKey, fieldType: f.fieldType })));
      })
      .catch(() => {});

  useEffect(() => {
    api.get('/field-definitions', { params: { entityType: 'ticket' } })
      .then(r => {
        setTicketFieldKeys(r.data.map((f: any) => f.fieldKey));
        setTicketFieldCatalog(r.data.map((f: any) => ({ fieldKey: f.fieldKey, fieldType: f.fieldType })));
      })
      .catch(() => {});
    reloadWorkflowFields();
    reloadLibraryEntries();
  }, []);

  const reloadLibraryEntries = () =>
    api.get('/action-item-library').then(r => setLibraryEntries(r.data)).catch(() => {});

  const existingLibraryEntries = libraryEntries.filter(e => e.type === actionType);
  const aiLibraryEntries = libraryEntries.filter(e => e.source === 'ai');

  const handleEditExisting = (entry: LibraryEntry) => {
    setActionType(entry.type as TargetType);
    setNodeTitle(entry.name);
    let hasResponseMapping = false;
    if (entry.type === 'mcp_tool') {
      const cfg = entry.typeConfig as { serverUrl?: string; auth?: McpAuth; calls?: McpCall[]; fieldMappings?: { response?: McpResponseMapping[] } } | null;
      setMcpServerUrl(cfg?.serverUrl ?? '');
      setMcpAuth(cfg?.auth ?? { type: 'none' });
      setMcpDiscoveredTools([]);
      setMcpDraftCalls(cfg?.calls ?? []);
      setMcpDraftMappings(cfg?.fieldMappings?.response ?? []);
      hasResponseMapping = (cfg?.fieldMappings?.response?.length ?? 0) > 0;
    } else {
      const cfg = entry.typeConfig as {
        calls?: ExternalApiCall[]; fieldMappings?: ExternalApiFieldMappings;
        aiWizard?: {
          documentation?: string; intent?: string; sessionId?: number | null;
          discoveredEndpoints?: DiscoveredEndpoint[]; selectedEndpointId?: string | null;
          requiredInputs?: RequiredInput[];
        };
      } | null;
      setDraftCalls(cfg?.calls ?? []);
      setDraftMappings(cfg?.fieldMappings ?? emptyMappings);
      setActiveCallId(cfg?.calls?.[0]?.id ?? null);
      setDocumentation(cfg?.aiWizard?.documentation ?? '');
      setIntent(cfg?.aiWizard?.intent ?? '');
      setWizardSessionId(cfg?.aiWizard?.sessionId ?? null);
      setDiscoveredEndpoints(cfg?.aiWizard?.discoveredEndpoints ?? []);
      setSelectedEndpointId(cfg?.aiWizard?.selectedEndpointId ?? null);
      setRequiredInputs(cfg?.aiWizard?.requiredInputs ?? []);
      hasResponseMapping = (cfg?.fieldMappings?.response?.length ?? 0) > 0;
    }
    setResponseMapped(hasResponseMapping);
    setLastTestResult(null);
    setTestSampleValues({});
    setTargetMode('existing');
    setTargetNodeId(String(entry.id));
    setCameFromList(true);
    setGenError('');
    setSaveError('');
    // Editing an existing library entry has no fresh AI draft, so no pending suggestions apply.
    setMissingWorkflowFields([]);
    setDiscoverError('');
    setSkeletonError('');
    setMappingError('');
    setMappingResponseError('');
    setResponseMapProposal(null);
    setMode('wizard');
    setStep(inferResumeStep(entry));
  };

  const handleDeleteExisting = async (entry: LibraryEntry) => {
    if (!window.confirm(t('action_item_library_delete_confirm', { defaultValue: 'Delete this action item from the library?' }))) return;
    await api.delete(`/action-item-library/${entry.id}`);
    await reloadLibraryEntries();
  };

  // Step 1 (external_api) — fetches a documentation URL's raw content server-side (avoids a
  // browser CORS block) straight into the Documentation textarea, for review/editing before
  // Discover Endpoints runs.
  const handleFetchDocumentationUrl = async () => {
    setFetchDocError('');
    setFetchingDoc(true);
    try {
      const res = await api.post('/templates/fetch-documentation-url', { url: documentationUrl });
      setDocumentation(res.data.content ?? '');
    } catch (err: any) {
      setFetchDocError(err?.response?.data?.message || t('awb_fetch_doc_failed', { defaultValue: 'Could not fetch this URL.' }));
    } finally {
      setFetchingDoc(false);
    }
  };

  // Step 1 (external_api) — parses the pasted documentation into every distinct endpoint it
  // describes, continuing (or starting) the shared wizard session.
  const handleDiscoverEndpoints = async () => {
    setDiscoverError('');
    setDiscovering(true);
    try {
      const res = await api.post('/templates/ai-discover-endpoints', {
        documentation, intent, sessionId: wizardSessionId,
      });
      const endpoints = (res.data.endpoints ?? []) as DiscoveredEndpoint[];
      const sessId = res.data.sessionId ?? wizardSessionId;
      if (res.data.sessionId) setWizardSessionId(res.data.sessionId);
      setDiscoveredEndpoints(endpoints);
      setSelectedEndpointId(null);
      await autoSaveDraft({ discoveredEndpoints: endpoints, selectedEndpointId: null, sessionId: sessId });
      setStep(2);
    } catch (err: any) {
      setDiscoverError(err?.response?.data?.message || t('awb_discover_failed', { defaultValue: 'Could not discover endpoints — check that an AI provider is configured and active.' }));
    } finally {
      setDiscovering(false);
    }
  };

  // Step 2 (external_api) — drafts a call skeleton + required inputs for exactly the selected
  // endpoint, continuing the same session Step 1 started.
  const handleDraftSkeleton = async (endpoint: DiscoveredEndpoint) => {
    setSkeletonError('');
    setSkeletonLoading(true);
    try {
      const res = await api.post('/templates/ai-draft-call-skeleton', {
        sessionId: wizardSessionId, intent, selectedEndpoint: endpoint,
      });
      const sessId = res.data.sessionId ?? wizardSessionId;
      if (res.data.sessionId) setWizardSessionId(res.data.sessionId);
      const call = res.data.call as ExternalApiCall;
      const inputs = (res.data.requiredInputs ?? []) as RequiredInput[];
      setDraftCalls([call]);
      setActiveCallId(call.id);
      setRequiredInputs(inputs);
      setSelectedEndpointId(endpoint.id);
      // Seed one editable row per required input immediately — every real parameter is visible
      // and editable right away, without waiting on (or depending on) "Map Fields with AI"
      // succeeding first. Defaults to the first ticket field, same convention the mapping editor's
      // own "+ Add" button already uses for a fresh row; the admin corrects each one from there.
      const defaultTicketField = `ticket.${ticketFieldCatalog[0]?.fieldKey ?? 'title'}`;
      const seededMappings: ExternalApiFieldMappings = { request: inputs.map(inp => ({ placeholder: inp.placeholder, ticketField: defaultTicketField })), response: [] };
      setDraftMappings(seededMappings);
      setResponseMapped(false);
      setLastTestResult(null);
      setTestSampleValues({});
      const title = endpoint.title || (intent.trim() ? intent.trim().slice(0, 60) : t('awb_default_action_title', { defaultValue: 'AI Workflow Action' }));
      setNodeTitle(title);
      await autoSaveDraft({
        draftCalls: [call], draftMappings: seededMappings, requiredInputs: inputs,
        selectedEndpointId: endpoint.id, sessionId: sessId, nodeTitle: title,
      });
      setStep(3);
    } catch (err: any) {
      setSkeletonError(err?.response?.data?.message || t('awb_draft_skeleton_failed', { defaultValue: 'Could not draft this call — try a different endpoint or AI provider/model.' }));
    } finally {
      setSkeletonLoading(false);
    }
  };

  // Step 3 (external_api) — maps each required input to a real ticket/workflow field, continuing
  // the same session Steps 1-2 already used.
  const handleMapFields = async () => {
    setMappingError('');
    setMappingLoading(true);
    try {
      const res = await api.post('/templates/ai-map-call-fields', {
        sessionId: wizardSessionId, documentation, intent, requiredInputs,
        ticketFields: ticketFieldCatalog.map(f => ({ key: f.fieldKey, type: f.fieldType })),
        workflowFields: workflowFieldCatalog.map(f => ({ key: f.fieldKey, type: f.fieldType })),
      });
      const sessId = res.data.sessionId ?? wizardSessionId;
      if (res.data.sessionId) setWizardSessionId(res.data.sessionId);
      // Merge by placeholder rather than replacing wholesale — every row is already seeded (see
      // handleDraftSkeleton), and the AI may map only some of them (or none, if it fails); this
      // updates whichever ones it addressed and leaves every other row (including anything the
      // admin already hand-edited) untouched, rather than wiping the table back down to just the
      // AI's own answer.
      const aiMappings = (res.data.requestMappings ?? []) as FieldMappingRequest[];
      let mergedMappings!: ExternalApiFieldMappings;
      setDraftMappings(prev => {
        const byPlaceholder = new Map(aiMappings.map(m => [m.placeholder, m]));
        const merged = prev.request.map(r => byPlaceholder.get(r.placeholder) ?? r);
        const existingPlaceholders = new Set(prev.request.map(r => r.placeholder));
        const added = aiMappings.filter(m => !existingPlaceholders.has(m.placeholder));
        mergedMappings = { ...prev, request: [...merged, ...added] };
        return mergedMappings;
      });
      const missing = (res.data.missingWorkflowFields ?? []) as WorkflowFieldSuggestion[];
      setMissingWorkflowFields(prev => {
        const existingKeys = new Set(prev.map(s => s.suggestedFieldKey));
        return [...prev, ...missing.filter(s => !existingKeys.has(s.suggestedFieldKey))];
      });
      await autoSaveDraft({ draftMappings: mergedMappings, sessionId: sessId });
    } catch (err: any) {
      setMappingError(err?.response?.data?.message || t('awb_map_fields_failed', { defaultValue: 'Could not map fields — try a different AI provider/model.' }));
    } finally {
      setMappingLoading(false);
    }
  };

  // Step 5 (external_api) — grounds a response-mapping proposal in Step 4's already-captured real
  // response (never re-running the live call just to get response data), continuing the session.
  const handleMapResponse = async () => {
    if (!lastTestResult?.callTrace) return;
    setMappingResponseError('');
    setMappingResponseLoading(true);
    setResponseMapProposal(null);
    try {
      const rawCalls = draftCalls.map(c => {
        const trace = lastTestResult.callTrace!.find((tr: any) => tr.callId === c.id);
        return {
          id: c.id,
          name: c.name,
          existingResponseCaptures: c.responseCaptures,
          rawResponse: trace?.rawResponse ?? trace?.rawResult ?? '',
        };
      });
      const res = await api.post('/templates/ai-refine-response-mapping', {
        type: 'external_api',
        intent, documentation,
        ticketFields: ticketFieldCatalog.map(f => ({ key: f.fieldKey, type: f.fieldType })),
        workflowFields: workflowFieldCatalog.map(f => ({ key: f.fieldKey, type: f.fieldType })),
        calls: rawCalls,
        sessionId: wizardSessionId,
      });
      if (res.data.sessionId) setWizardSessionId(res.data.sessionId);
      setResponseMapProposal({
        calls: res.data.calls ?? [],
        fieldMappingsResponse: res.data.fieldMappings?.response ?? [],
        missingWorkflowFields: res.data.missingWorkflowFields ?? [],
      });
    } catch (err: any) {
      setMappingResponseError(err?.response?.data?.message || t('test_action_auto_map_failed', { defaultValue: 'Could not generate a mapping suggestion.' }));
    } finally {
      setMappingResponseLoading(false);
    }
  };

  const applyResponseMapProposal = () => {
    if (!responseMapProposal) return;
    handleApplyAutoMap(responseMapProposal);
    setResponseMapProposal(null);
  };

  // Re-evaluates the applied responseCaptures' JsonPaths against Step 4's already-captured
  // response (see /templates/evaluate-response-captures) — no new live call, so verifying a
  // mapping never means running a real, possibly side-effecting API call twice in one wizard visit.
  const handleVerifyCaptures = async () => {
    if (!lastTestResult?.callTrace) return;
    setVerifyCapturesError('');
    setVerifyingCaptures(true);
    setVerifiedCapturedValues(null);
    try {
      const calls = draftCalls.map(c => {
        const trace = lastTestResult.callTrace!.find((tr: any) => tr.callId === c.id);
        return {
          id: c.id,
          name: c.name,
          existingResponseCaptures: c.responseCaptures,
          rawResponse: trace?.rawResponse ?? trace?.rawResult ?? '',
        };
      });
      const res = await api.post('/templates/evaluate-response-captures', { calls });
      if (res.data.success) {
        setVerifiedCapturedValues(res.data.capturedValues ?? {});
        // A partial miss (some captures resolved, some didn't) is still "success" so the ones
        // that worked stay visible below, but the specific per-field failure reason must not be
        // silently dropped — that's exactly how a wrong JSONPath went unnoticed here before.
        if (res.data.error) setVerifyCapturesError(res.data.error);
      } else {
        setVerifyCapturesError(res.data.error || t('awb_verify_captures_failed', { defaultValue: 'Could not verify captures.' }));
      }
    } catch (err: any) {
      setVerifyCapturesError(err?.response?.data?.message || t('awb_verify_captures_failed', { defaultValue: 'Could not verify captures.' }));
    } finally {
      setVerifyingCaptures(false);
    }
  };

  // MCP-only now — external_api's draft is built via the discover/skeleton/map-fields steps above.
  const handleGenerate = async () => {
    setGenError('');
    setGenerating(true);
    try {
      const workflowFields = workflowFieldCatalog.map(f => ({ key: f.fieldKey, type: f.fieldType }));
      const ticketFields = ticketFieldCatalog.map(f => ({ key: f.fieldKey, type: f.fieldType }));
      const res = await api.post('/templates/ai-suggest-mcp-action', {
        intent, tools: mcpDiscoveredTools, ticketFields, workflowFields,
      });
      const draft = res.data;
      const mcpCalls: McpCall[] = draft.calls ?? [];
      const mcpMappings: McpResponseMapping[] = draft.fieldMappings?.response ?? [];
      setMcpDraftCalls(mcpCalls);
      setMcpDraftMappings(mcpMappings);
      setMissingWorkflowFields(prev => {
        const existingKeys = new Set(prev.map(s => s.suggestedFieldKey));
        return [...prev, ...(draft.missingWorkflowFields ?? []).filter((s: WorkflowFieldSuggestion) => !existingKeys.has(s.suggestedFieldKey))];
      });
      const title = intent.trim() ? intent.trim().slice(0, 60) : t('awb_default_action_title', { defaultValue: 'AI Workflow Action' });
      setNodeTitle(title);
      setCameFromList(false);
      setResponseMapped(false);
      setLastTestResult(null);
      setTestSampleValues({});
      await autoSaveDraft({ mcpDraftCalls: mcpCalls, mcpDraftMappings: mcpMappings, nodeTitle: title });
      setStep(3);
    } catch (err: any) {
      setGenError(err?.response?.data?.message || t('awb_generate_failed', { defaultValue: 'Failed to generate a draft — check that an AI provider is configured and active.' }));
    } finally {
      setGenerating(false);
    }
  };

  // `overrides` lets a caller supply values that were JUST set via setState in this same tick
  // (React state isn't updated synchronously, so reading e.g. `draftCalls` right after
  // `setDraftCalls(...)` in the same handler would see the stale pre-update value) — used by
  // autoSaveDraft's call sites right after an AI step's response lands; the manual "Save as
  // Draft"/"Save & Complete" buttons call this with no overrides, since by the time the admin
  // clicks one, the relevant state has already settled/rendered.
  const saveEntry = async (status: 'draft' | 'complete', overrides: Partial<{
    nodeTitle: string;
    draftCalls: ExternalApiCall[];
    draftMappings: ExternalApiFieldMappings;
    discoveredEndpoints: DiscoveredEndpoint[];
    selectedEndpointId: string | null;
    requiredInputs: RequiredInput[];
    sessionId: number | null;
    mcpDraftCalls: McpCall[];
    mcpDraftMappings: McpResponseMapping[];
  }> = {}) => {
    const finalMcpCalls = overrides.mcpDraftCalls ?? mcpDraftCalls;
    const finalMcpMappings = overrides.mcpDraftMappings ?? mcpDraftMappings;
    const finalCalls = overrides.draftCalls ?? draftCalls;
    const finalMappings = overrides.draftMappings ?? draftMappings;
    const finalDiscovered = overrides.discoveredEndpoints ?? discoveredEndpoints;
    const finalSelectedId = 'selectedEndpointId' in overrides ? overrides.selectedEndpointId! : selectedEndpointId;
    const finalRequiredInputs = overrides.requiredInputs ?? requiredInputs;
    const finalSessionId = 'sessionId' in overrides ? overrides.sessionId! : wizardSessionId;
    const finalNodeTitle = overrides.nodeTitle ?? nodeTitle;

    const typeConfig = actionType === 'mcp_tool'
      ? { serverUrl: mcpServerUrl, auth: mcpAuth, calls: finalMcpCalls, fieldMappings: { response: finalMcpMappings } }
      : {
          calls: finalCalls, fieldMappings: finalMappings,
          aiWizard: { documentation, intent, sessionId: finalSessionId, discoveredEndpoints: finalDiscovered, selectedEndpointId: finalSelectedId, requiredInputs: finalRequiredInputs },
        };
    const finalName = finalNodeTitle.trim() || t('awb_default_action_title', { defaultValue: 'AI Workflow Action' });
    const body = { name: finalName, type: actionType, typeConfig, source: 'ai', status };

    if (targetMode === 'existing' && targetNodeId) {
      await api.put(`/action-item-library/${targetNodeId}`, body);
    } else {
      const res = await api.post('/action-item-library', body);
      setTargetMode('existing');
      setTargetNodeId(String(res.data.id));
    }
    await reloadLibraryEntries();
  };

  // Silently persists current progress as a draft — called after each wizard step so nothing is
  // lost if the admin closes the tab or the browser crashes mid-flow. Best-effort: a failure here
  // must never block wizard navigation (the manual "Save as Draft" button still surfaces errors).
  const autoSaveDraft = async (overrides: Parameters<typeof saveEntry>[1] = {}) => {
    const hasContent = actionType === 'mcp_tool'
      ? (overrides.mcpDraftCalls ?? mcpDraftCalls).length > 0 || intent.trim().length > 0
      : (overrides.draftCalls ?? draftCalls).length > 0 || documentation.trim().length > 0;
    if (!hasContent) return;
    try {
      await saveEntry('draft', overrides);
    } catch {
      // best-effort — swallow; the manual "Save as Draft" button surfaces this if it matters
    }
  };

  const handleSave = async () => {
    setSaveError('');
    setSaving(true);
    try {
      await saveEntry('complete');
      backToList();
    } catch (err: any) {
      setSaveError(err?.response?.data?.message || t('awb_save_failed', { defaultValue: 'Failed to save into the library.' }));
    } finally {
      setSaving(false);
    }
  };

  const handleSaveDraft = async () => {
    setSaveError('');
    if (!nodeTitle.trim()) {
      setSaveError(t('awb_draft_name_required', { defaultValue: 'Enter a name before saving as a draft.' }));
      return;
    }
    setSavingDraft(true);
    try {
      await saveEntry('draft');
      backToList();
    } catch (err: any) {
      setSaveError(err?.response?.data?.message || t('awb_save_failed', { defaultValue: 'Failed to save into the library.' }));
    } finally {
      setSavingDraft(false);
    }
  };

  const startOver = () => {
    setMode('wizard');
    setStep(1);
    setIntent('');
    setDocumentation('');
    setDraftCalls([]);
    setDraftMappings(emptyMappings);
    setMcpServerUrl('');
    setMcpAuth({ type: 'none' });
    setMcpDiscoveredTools([]);
    setMcpDraftCalls([]);
    setMcpDraftMappings([]);
    setNodeTitle('');
    setTargetMode('new');
    setTargetNodeId('');
    setCameFromList(false);
    setGenError('');
    setSaveError('');
    setMissingWorkflowFields([]);
    setResponseMapped(false);
    // Drop the reference — the abandoned ai_chat_sessions row is left as-is, same as an abandoned draft.
    setWizardSessionId(null);
    setDocumentationUrl('');
    setFetchingDoc(false);
    setFetchDocError('');
    setDiscovering(false);
    setDiscoverError('');
    setDiscoveredEndpoints([]);
    setSelectedEndpointId(null);
    setSkeletonLoading(false);
    setSkeletonError('');
    setRequiredInputs([]);
    setActiveCallId(null);
    setMappingLoading(false);
    setMappingError('');
    setPreviewSampleValues({});
    setLastTestResult(null);
    setTestSampleValues({});
    setMappingResponseLoading(false);
    setMappingResponseError('');
    setResponseMapProposal(null);
  };

  const backToList = () => {
    setMode('list');
    reloadLibraryEntries();
  };

  const captureNames = draftCalls.flatMap(c => c.responseCaptures.map(r => r.name).filter(Boolean));
  const mcpCaptureNames = mcpDraftCalls.flatMap(c => c.responseCaptures.map(r => r.name).filter(Boolean));

  // Where a suggested "this.<key>" is actually referenced in the active draft — shown alongside
  // each suggestion so the admin can see why it was proposed, without the backend needing to send
  // a redundant pointer back.
  const missingFieldUsedBy = (key: string): string[] => {
    const needle = `this.${key}`;
    const hits: string[] = [];
    if (actionType === 'mcp_tool') {
      mcpDraftCalls.forEach(c => c.argumentMappings.forEach(a => {
        if (a.ticketField === needle) hits.push(`${c.toolName}.${a.toolArgument}`);
      }));
      mcpDraftMappings.forEach(m => { if (m.target === needle) hits.push(`response: ${m.captureName}`); });
    } else {
      draftMappings.request.forEach(r => { if (r.ticketField === needle) hits.push(`{{${r.placeholder}}}`); });
      draftMappings.response.forEach(r => { if (r.target === needle) hits.push(`response: ${r.captureName}`); });
    }
    return hits;
  };

  const handleFieldCreated = (key: string) => {
    setMissingWorkflowFields(prev => prev.filter(s => s.suggestedFieldKey !== key));
    reloadWorkflowFields();
  };

  // Applies an "Auto-map from this response"/"Map Response with AI" proposal into the current
  // draft — reached only via an explicit admin click after reviewing the proposal, never
  // automatically. Merges captures by call id (leaving untested calls untouched), replaces the
  // response mapping wholesale (the proposal is a complete re-derivation of it), folds any new
  // missingWorkflowFields suggestions into the existing pending list, and unlocks Review & Save.
  const handleApplyAutoMap = async (proposal: AutoMapProposal) => {
    let overrides: Parameters<typeof saveEntry>[1] = {};
    if (actionType === 'mcp_tool') {
      let mergedMcpCalls!: McpCall[];
      setMcpDraftCalls(prev => { mergedMcpCalls = mergeCapturesById(prev, proposal.calls); return mergedMcpCalls; });
      setMcpDraftMappings(proposal.fieldMappingsResponse);
      overrides = { mcpDraftCalls: mergedMcpCalls, mcpDraftMappings: proposal.fieldMappingsResponse };
    } else {
      let mergedCalls!: ExternalApiCall[];
      setDraftCalls(prev => { mergedCalls = mergeCapturesById(prev, proposal.calls); return mergedCalls; });
      let mergedMappings!: ExternalApiFieldMappings;
      setDraftMappings(prev => { mergedMappings = { ...prev, response: proposal.fieldMappingsResponse }; return mergedMappings; });
      overrides = { draftCalls: mergedCalls, draftMappings: mergedMappings };
    }
    setMissingWorkflowFields(prev => {
      const existingKeys = new Set(prev.map(s => s.suggestedFieldKey));
      return [...prev, ...proposal.missingWorkflowFields.filter(s => !existingKeys.has(s.suggestedFieldKey))];
    });
    setResponseMapped(true);
    await autoSaveDraft(overrides);
  };

  // Applies an "Ask AI"/"Fix with AI" call adjustment (see AiAgentAdjustPanel.tsx) — external_api
  // only. Replaces the one adjusted call in place by id and swaps in the corrected request field
  // mappings wholesale (the adjustment is a complete re-derivation of them, same as
  // handleApplyAutoMap does for the response side); also carries the session id forward so any
  // further AI action in this visit keeps the same conversation.
  const handleApplyCallFix = async (fix: AiAgentAdjustProposal) => {
    let mergedCalls!: ExternalApiCall[];
    setDraftCalls(prev => {
      mergedCalls = prev.map(c => (c.id === fix.call.id ? { ...c, ...fix.call } as ExternalApiCall : c));
      return mergedCalls;
    });
    let mergedMappings!: ExternalApiFieldMappings;
    setDraftMappings(prev => {
      mergedMappings = { ...prev, request: fix.requestMappings };
      return mergedMappings;
    });
    setWizardSessionId(fix.sessionId);
    await autoSaveDraft({ draftCalls: mergedCalls, draftMappings: mergedMappings, sessionId: fix.sessionId });
  };

  const hasCalls = actionType === 'mcp_tool' ? mcpDraftCalls.length > 0 : draftCalls.length > 0;

  // Step 3 (external_api) — live URL/body preview, computed client-side, never executed.
  const activeCall = draftCalls.find(c => c.id === activeCallId) ?? draftCalls[0];

  // Wraps ExternalApiFieldMappingsEditor's onChange for the request-mapping table: whenever a row
  // is added/removed/renamed, keeps the active call's urlTemplate/bodyTemplate in sync (see
  // addPlaceholderToCall/removePlaceholderFromCall above) so the live preview — and the actual
  // saved call — genuinely reflects the mapping, not just the bookkeeping table.
  const handleMappingsChange = (next: ExternalApiFieldMappings) => {
    if (!activeCall) { setDraftMappings(next); return; }
    const prevPlaceholders = new Set(draftMappings.request.map(r => r.placeholder).filter(Boolean));
    const nextPlaceholders = new Set(next.request.map(r => r.placeholder).filter(Boolean));
    let call = activeCall;
    for (const p of prevPlaceholders) {
      if (!nextPlaceholders.has(p)) call = removePlaceholderFromCall(call, p);
    }
    for (const p of nextPlaceholders) {
      if (!prevPlaceholders.has(p) && !placeholderExistsInCall(call, p)) call = addPlaceholderToCall(call, p);
    }
    if (call !== activeCall) {
      setDraftCalls(prev => prev.map(c => (c.id === call.id ? call : c)));
    }
    setDraftMappings(next);
  };
  const previewSampleDefaults: Record<string, string> = {
    title: t('test_action_sample_title', { defaultValue: 'Sample Ticket Title' }) as string,
    description: t('test_action_sample_description', { defaultValue: 'Sample ticket description' }) as string,
    status: 'open',
    priority: 'medium',
  };
  const previewSampleValuesResolved: Record<string, string> = {};
  draftMappings.request.forEach(m => {
    const key = bareFieldKey(m.ticketField);
    previewSampleValuesResolved[key] = previewSampleValues[key] ?? previewSampleDefaults[key] ?? `sample_${key}`;
  });
  const previewVars = buildPreviewVars(draftMappings.request, previewSampleValuesResolved);
  const previewUrl = activeCall ? substituteForPreview(activeCall.urlTemplate, previewVars, true) : '';
  const previewBody = activeCall ? substituteForPreview(activeCall.bodyTemplate || '', previewVars, false) : '';

  if (mode === 'list') {
    return (
      <div className="awb-wrap">
        <div className="ail-toolbar">
          <p className="ail-hint">
            {t('awb_list_hint', { defaultValue: 'AI-built action items (external API calls or MCP tool calls). Add one to any template from the Workflow Designer.' })}
          </p>
          <button className="ail-add-btn" onClick={startOver}>
            <Plus size={14} /> {t('awb_new_ai_item_btn', { defaultValue: 'New AI Action Item' })}
          </button>
        </div>

        {aiLibraryEntries.length === 0 ? (
          <div className="ail-state">{t('awb_ai_items_list_empty', { defaultValue: 'No AI action items yet — click "New AI Action Item" to build one.' })}</div>
        ) : (
          <div className="ail-list">
            {aiLibraryEntries.map(entry => (
              <div key={entry.id} className="ail-card-wrap">
                <div className="ail-card">
                  <span className="ail-card-icon">{TYPE_ICON[entry.type] ?? <Globe2 size={16} />}</span>
                  <div className="ail-card-body">
                    <span className="ail-card-name">{entry.name}</span>
                    <span className="ail-source-badge ail-source-ai"><Sparkles size={10} /> {t('action_item_library_ai_badge', { defaultValue: 'AI' })}</span>
                    <span className={`ail-source-badge ${entry.status === 'draft' ? 'ail-status-draft' : 'ail-status-complete'}`}>
                      {entry.status === 'draft' ? t('awb_status_draft_badge', { defaultValue: 'Draft' }) : t('awb_status_complete_badge', { defaultValue: 'Complete' })}
                    </span>
                  </div>
                  <div className="ail-card-actions">
                    <button className="ail-icon-btn" onClick={() => handleEditExisting(entry)}><Pencil size={14} /></button>
                    <button className="ail-icon-btn ail-icon-delete" onClick={() => handleDeleteExisting(entry)}><Trash2 size={14} /></button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="awb-wrap">
      {/* Step indicator */}
      <div className="awb-steps">
        {(actionType === 'mcp_tool' ? MCP_STEP_BAR : EXTERNAL_API_STEP_BAR).map((s, i, arr) => (
          <div key={s.key} className={`awb-step${step === s.n ? ' active' : ''}${step > s.n ? ' done' : ''}`}>
            <span className="awb-step-num">{step > s.n ? <Check size={11} /> : i + 1}</span>
            <span className="awb-step-label">{t(s.key, { defaultValue: s.def })}</span>
            {i < arr.length - 1 && <span className="awb-step-connector" />}
          </div>
        ))}
      </div>

      {/* ── Step 1: Describe & Paste / Documentation ── */}
      {step === 1 && (
        <div className="awb-card">
          <button className="wfd-btn-ghost awb-back-to-list-btn" onClick={backToList}>
            <ArrowLeft size={13} /> {t('awb_back_to_list_btn', { defaultValue: 'Back to List' })}
          </button>
          <div className="awb-card-intro">
            <Sparkles size={16} className="awb-intro-icon" />
            <p>{actionType === 'mcp_tool'
              ? t('awb_intro_mcp', { defaultValue: "Point at an MCP server, discover its real tools, and describe what you want done — the AI picks the right tool and drafts the argument mapping from the server's actual schema. Response mapping happens next, after a real test call." })
              : t('awb_intro_external_api', { defaultValue: "Paste a 3rd-party API's documentation and describe what you want it to do — the AI drafts how to call it and which fields feed it as input. Response mapping happens next, after a real test call, grounded in the real response — never guessed here." })}</p>
          </div>

          <div className="awb-field">
            <label className="awb-label">{t('awb_action_type_label', { defaultValue: 'Action type' })}</label>
            <div className="awb-radio-row">
              <label className="awb-radio">
                <input type="radio" checked={actionType === 'external_api'} onChange={() => setActionType('external_api')} />
                {t('awb_action_type_external_api_option', { defaultValue: 'External API (HTTP docs)' })}
              </label>
              <label className="awb-radio">
                <input type="radio" checked={actionType === 'mcp_tool'} onChange={() => setActionType('mcp_tool')} />
                {t('awb_action_type_mcp_tool_option', { defaultValue: 'MCP Tool (server + discovery)' })}
              </label>
            </div>
          </div>

          <div className="awb-field">
            <label className="awb-label">{t('awb_intent_label', { defaultValue: 'What should this action do?' })}</label>
            <textarea
              className="wfd-inp awb-textarea-sm"
              value={intent}
              onChange={e => setIntent(e.target.value)}
              placeholder={t('awb_intent_placeholder', { defaultValue: "e.g. Order a new laptop for a new hire from our vendor's ordering API, and capture the order confirmation ID" }) as string}
            />
          </div>

          {actionType === 'mcp_tool' ? (
            <div className="awb-field">
              <label className="awb-label">{t('awb_mcp_server_label', { defaultValue: 'MCP server' })}</label>
              <McpServerConnectionEditor
                serverUrl={mcpServerUrl}
                onServerUrlChange={setMcpServerUrl}
                auth={mcpAuth}
                onAuthChange={setMcpAuth}
                onToolsDiscovered={setMcpDiscoveredTools}
              />
              {mcpDiscoveredTools.length > 0 && (
                <p className="awb-hint">{t('awb_tools_discovered_count', { defaultValue: '{{count}} tool{{s}} discovered — ready to draft.', count: mcpDiscoveredTools.length, s: mcpDiscoveredTools.length !== 1 ? 's' : '' })}</p>
              )}
            </div>
          ) : (
            <>
              <div className="awb-field">
                <label className="awb-label">{t('awb_documentation_url_label', { defaultValue: 'Or fetch from a URL' })}</label>
                <div className="awb-match-row">
                  <input
                    className="wfd-inp"
                    style={{ flex: 1 }}
                    value={documentationUrl}
                    onChange={e => setDocumentationUrl(e.target.value)}
                    placeholder={t('awb_documentation_url_placeholder', { defaultValue: 'https://example.com/api-docs' }) as string}
                  />
                  <button className="wfd-btn-ghost" type="button" onClick={handleFetchDocumentationUrl} disabled={fetchingDoc || !documentationUrl.trim()}>
                    {fetchingDoc
                      ? <><Loader2 size={13} className="awb-spin" /> {t('awb_fetching_doc_ellipsis', { defaultValue: 'Fetching…' })}</>
                      : t('awb_fetch_doc_btn', { defaultValue: 'Fetch' })}
                  </button>
                </div>
                {fetchDocError && <p className="awb-error">{fetchDocError}</p>}
              </div>

              <div className="awb-field">
                <label className="awb-label">{t('awb_api_documentation_label', { defaultValue: 'API documentation' })}</label>
                <textarea
                  className="wfd-inp awb-textarea-lg"
                  value={documentation}
                  onChange={e => setDocumentation(e.target.value)}
                  placeholder={t('awb_api_documentation_placeholder', { defaultValue: "Paste the vendor's API docs here — endpoint URLs, request/response examples, auth scheme, etc." }) as string}
                />
              </div>
            </>
          )}

          {(actionType === 'mcp_tool' ? genError : discoverError) && (
            <p className="awb-error">{actionType === 'mcp_tool' ? genError : discoverError}</p>
          )}

          <div className="awb-actions">
            <button
              className="wfd-btn-save"
              disabled={
                actionType === 'mcp_tool'
                  ? (generating || mcpDiscoveredTools.length === 0)
                  : (discovering || !documentation.trim())
              }
              onClick={actionType === 'mcp_tool' ? handleGenerate : handleDiscoverEndpoints}
            >
              {actionType === 'mcp_tool'
                ? (generating
                    ? <><Loader2 size={13} className="awb-spin" /> {t('awb_generating_ellipsis', { defaultValue: 'Generating…' })}</>
                    : <><Sparkles size={13} /> {t('awb_generate_draft_btn', { defaultValue: 'Generate Draft' })}</>)
                : (discovering
                    ? <><Loader2 size={13} className="awb-spin" /> {t('awb_discovering_ellipsis', { defaultValue: 'Discovering…' })}</>
                    : <><Sparkles size={13} /> {t('awb_discover_endpoints_btn', { defaultValue: 'Discover Endpoints with AI' })}</>)}
            </button>
          </div>
        </div>
      )}

      {/* ── Step 2: Select Endpoint (external_api only) ── */}
      {step === 2 && actionType === 'external_api' && (
        <div className="awb-card">
          <p className="awb-hint">{t('awb_select_endpoint_hint', { defaultValue: 'Pick the endpoint this action should call.' })}</p>

          <div className="awb-endpoint-list">
            {discoveredEndpoints.map(ep => (
              <label key={ep.id} className={`awb-endpoint-card${selectedEndpointId === ep.id ? ' selected' : ''}`}>
                <input type="radio" name="awb-endpoint" checked={selectedEndpointId === ep.id} onChange={() => setSelectedEndpointId(ep.id)} />
                <div className="awb-endpoint-card-body">
                  <div className="awb-endpoint-card-head">
                    <span className="awb-endpoint-method">{ep.method}</span>
                    <span className="awb-endpoint-title">{ep.title}</span>
                    {ep.recommended && <span className="awb-endpoint-badge">{t('awb_endpoint_recommended_badge', { defaultValue: 'Recommended' })}</span>}
                  </div>
                  <p className="awb-endpoint-summary">{ep.summary}</p>
                </div>
              </label>
            ))}
            {discoveredEndpoints.length === 0 && (
              <p className="awb-hint">{t('awb_no_endpoints_found', { defaultValue: 'No endpoints found in this documentation yet.' })}</p>
            )}
          </div>

          {skeletonError && <p className="awb-error">{skeletonError}</p>}

          <div className="awb-actions">
            <button className="wfd-btn-ghost" onClick={() => setStep(1)}><ArrowLeft size={13} /> {t('back_btn', { defaultValue: 'Back' })}</button>
            <button
              className="wfd-btn-save"
              disabled={skeletonLoading || !selectedEndpointId}
              onClick={() => {
                const ep = discoveredEndpoints.find(e => e.id === selectedEndpointId);
                if (ep) handleDraftSkeleton(ep);
              }}
            >
              {skeletonLoading
                ? <><Loader2 size={13} className="awb-spin" /> {t('awb_drafting_skeleton_ellipsis', { defaultValue: 'Drafting…' })}</>
                : <><Sparkles size={13} /> {t('awb_draft_skeleton_btn', { defaultValue: 'Use This Endpoint' })}</>}
            </button>
          </div>
        </div>
      )}

      {/* ── Step 3: Field Mapping (external_api only) ── */}
      {step === 3 && actionType === 'external_api' && (
        <div className="awb-card">
          <div className="awb-field">
            <label className="awb-label">{t('awb_action_item_title_label', { defaultValue: 'Action item title' })}</label>
            <input className="wfd-inp" value={nodeTitle} onChange={e => setNodeTitle(e.target.value)} placeholder={t('awb_action_item_title_placeholder', { defaultValue: 'Order Laptop' }) as string} />
          </div>

          <WorkflowFieldSuggestions suggestions={missingWorkflowFields} usedBy={missingFieldUsedBy} onCreated={handleFieldCreated} />

          <div className="awb-field">
            <label className="awb-label">{t('awb_api_calls_label', { defaultValue: 'API Calls' })}</label>
            <ExternalApiCallsEditor calls={draftCalls} onChange={setDraftCalls} />
          </div>

          <div className="awb-field">
            <div className="awb-match-row">
              <button className="wfd-btn-ghost" type="button" onClick={handleMapFields} disabled={mappingLoading || requiredInputs.length === 0}>
                {mappingLoading
                  ? <><Loader2 size={13} className="awb-spin" /> {t('awb_mapping_fields_ellipsis', { defaultValue: 'Mapping…' })}</>
                  : <><Sparkles size={13} /> {t('awb_map_fields_btn', { defaultValue: 'Map Fields with AI' })}</>}
              </button>
            </div>
            {mappingError && <p className="awb-error">{mappingError}</p>}
            <ExternalApiFieldMappingsEditor
              mappings={draftMappings}
              onChange={handleMappingsChange}
              ticketFieldKeys={ticketFieldKeys}
              workflowFieldKeys={workflowFieldKeys}
              captureNames={captureNames}
              showResponse={false}
            />
          </div>

          {activeCall && (
            <div className="awb-field">
              {Object.keys(previewSampleValuesResolved).length > 0 && (
                <>
                  <label className="awb-label">{t('sample_ticket_values_label', { defaultValue: 'SAMPLE TICKET VALUES' })}</label>
                  {Object.keys(previewSampleValuesResolved).map(k => (
                    <div key={k} className="tam-field-row">
                      <span className="tam-field-key">{k}</span>
                      <input
                        className="wfd-inp"
                        value={previewSampleValues[k] ?? previewSampleValuesResolved[k]}
                        onChange={e => setPreviewSampleValues(prev => ({ ...prev, [k]: e.target.value }))}
                      />
                    </div>
                  ))}
                </>
              )}
              <label className="awb-label" style={{ marginTop: 10 }}>{t('awb_url_preview_label', { defaultValue: 'Live URL Preview' })}</label>
              <div className="awb-preview-box">{previewUrl}</div>
              {activeCall.method !== 'GET' && activeCall.bodyTemplate && (
                <>
                  <label className="awb-label" style={{ marginTop: 10 }}>{t('awb_body_preview_label', { defaultValue: 'Request Body Preview' })}</label>
                  <pre className="awb-preview-box awb-preview-box-pre">{previewBody}</pre>
                </>
              )}
            </div>
          )}

          {activeCall && (
            <AiAgentAdjustPanel
              call={activeCall as unknown as Record<string, unknown>}
              requestMappings={draftMappings.request}
              sessionId={wizardSessionId}
              documentation={documentation}
              intent={intent}
              ticketFields={ticketFieldCatalog.map(f => ({ key: f.fieldKey, type: f.fieldType }))}
              workflowFieldCatalog={workflowFieldCatalog.map(f => ({ key: f.fieldKey, type: f.fieldType }))}
              onApply={handleApplyCallFix}
            />
          )}

          <div className="awb-actions">
            <button className="wfd-btn-ghost" onClick={cameFromList ? backToList : () => setStep(2)}><ArrowLeft size={13} /> {t('back_btn', { defaultValue: 'Back' })}</button>
            <button className="wfd-btn-save" onClick={async () => { await autoSaveDraft(); setStep(4); }}>
              {t('awb_continue_btn', { defaultValue: 'Continue' })} <ArrowRight size={13} />
            </button>
          </div>
        </div>
      )}

      {/* ── Step 3 (MCP): Test & Map — unchanged ── */}
      {step === 3 && actionType === 'mcp_tool' && (
        <div className="awb-card">
          <div className="awb-field">
            <label className="awb-label">{t('awb_action_item_title_label', { defaultValue: 'Action item title' })}</label>
            <input className="wfd-inp" value={nodeTitle} onChange={e => setNodeTitle(e.target.value)} placeholder={t('awb_action_item_title_placeholder', { defaultValue: 'Order Laptop' }) as string} />
          </div>

          <WorkflowFieldSuggestions suggestions={missingWorkflowFields} usedBy={missingFieldUsedBy} onCreated={handleFieldCreated} />

          <div className="awb-field">
            <label className="awb-label">{t('awb_mcp_server_label', { defaultValue: 'MCP server' })}</label>
            <McpServerConnectionEditor
              serverUrl={mcpServerUrl}
              onServerUrlChange={setMcpServerUrl}
              auth={mcpAuth}
              onAuthChange={setMcpAuth}
              onToolsDiscovered={setMcpDiscoveredTools}
            />
            <div className="awb-label" style={{ marginTop: 10 }}>{t('awb_tool_calls_label', { defaultValue: 'Tool Calls' })}</div>
            <McpToolPicker tools={mcpDiscoveredTools} onPick={tool => {
              const properties = tool?.inputSchema?.properties ?? {};
              setMcpDraftCalls(prev => [...prev, {
                id: crypto.randomUUID(), order: prev.length, toolName: tool.name,
                argumentMappings: Object.keys(properties).map(key => ({ toolArgument: key, ticketField: '' })),
                responseCaptures: [],
              }]);
            }} />
            <McpToolCallsEditor
              calls={mcpDraftCalls} onChange={setMcpDraftCalls}
              ticketFieldKeys={ticketFieldKeys} workflowFieldKeys={workflowFieldKeys}
            />
          </div>

          <div className="awb-field">
            <label className="awb-label">{t('awb_run_test_label', { defaultValue: 'Run a real test' })}</label>
            <p className="awb-hint">{t('awb_run_test_hint', { defaultValue: 'A real response is required before AI can map response fields — nothing is guessed here.' })}</p>
            {hasCalls ? (
              <TestActionModal
                inline
                type={actionType}
                typeConfig={{ serverUrl: mcpServerUrl, auth: mcpAuth, calls: mcpDraftCalls, fieldMappings: { response: mcpDraftMappings } }}
                referencedTicketFields={mcpDraftCalls.flatMap(c => c.argumentMappings).map(m => m.ticketField).filter((f): f is string => !!f)}
                ticketFields={ticketFieldCatalog.map(f => ({ key: f.fieldKey, type: f.fieldType }))}
                workflowFieldCatalog={workflowFieldCatalog.map(f => ({ key: f.fieldKey, type: f.fieldType }))}
                intent={intent}
                documentation={documentation}
                onApplyMapping={handleApplyAutoMap}
                onWorkflowFieldCreated={handleFieldCreated}
                sampleValues={testSampleValues}
                onSampleValuesChange={setTestSampleValues}
                result={lastTestResult}
                onResultChange={setLastTestResult}
              />
            ) : (
              <p className="awb-hint">{t('awb_no_calls_yet', { defaultValue: 'Add at least one call above before testing.' })}</p>
            )}
          </div>

          {saveError && <p className="awb-error">{saveError}</p>}

          <div className="awb-actions">
            <button className="wfd-btn-ghost" onClick={cameFromList ? backToList : () => setStep(1)}><ArrowLeft size={13} /> {t('back_btn', { defaultValue: 'Back' })}</button>
            <div className="awb-actions-group">
              <button className="wfd-btn-ghost" disabled={!hasCalls || savingDraft} onClick={handleSaveDraft}>
                {savingDraft ? <><Loader2 size={13} className="awb-spin" /> {t('saving', { defaultValue: 'Saving…' })}</> : t('awb_save_draft_btn', { defaultValue: 'Save as Draft' })}
              </button>
              <button className="wfd-btn-save" disabled={!responseMapped} onClick={async () => { await autoSaveDraft(); setStep(4); }}>
                {t('awb_continue_btn', { defaultValue: 'Continue' })} <ArrowRight size={13} />
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ── Step 4: Test (external_api only) ── */}
      {step === 4 && actionType === 'external_api' && (
        <div className="awb-card">
          <div className="awb-field">
            <label className="awb-label">{t('awb_action_item_title_label', { defaultValue: 'Action item title' })}</label>
            <input className="wfd-inp" value={nodeTitle} onChange={e => setNodeTitle(e.target.value)} placeholder={t('awb_action_item_title_placeholder', { defaultValue: 'Order Laptop' }) as string} />
          </div>

          <WorkflowFieldSuggestions suggestions={missingWorkflowFields} usedBy={missingFieldUsedBy} onCreated={handleFieldCreated} />

          <div className="awb-field">
            <label className="awb-label">{t('awb_run_test_label', { defaultValue: 'Run a real test' })}</label>
            {hasCalls ? (
              <TestActionModal
                inline
                type="external_api"
                typeConfig={{ calls: draftCalls, fieldMappings: draftMappings }}
                referencedTicketFields={draftMappings.request.map(r => r.ticketField)}
                ticketFields={ticketFieldCatalog.map(f => ({ key: f.fieldKey, type: f.fieldType }))}
                workflowFieldCatalog={workflowFieldCatalog.map(f => ({ key: f.fieldKey, type: f.fieldType }))}
                intent={intent}
                documentation={documentation}
                onWorkflowFieldCreated={handleFieldCreated}
                sessionId={wizardSessionId}
                requestMappings={draftMappings.request}
                onApplyCallFix={handleApplyCallFix}
                sampleValues={testSampleValues}
                onSampleValuesChange={setTestSampleValues}
                result={lastTestResult}
                onResultChange={setLastTestResult}
              />
            ) : (
              <p className="awb-hint">{t('awb_no_calls_yet', { defaultValue: 'Add at least one call above before testing.' })}</p>
            )}
          </div>

          {saveError && <p className="awb-error">{saveError}</p>}

          <div className="awb-actions">
            <button className="wfd-btn-ghost" onClick={() => setStep(3)}><ArrowLeft size={13} /> {t('back_btn', { defaultValue: 'Back' })}</button>
            <div className="awb-actions-group">
              <button className="wfd-btn-ghost" disabled={!hasCalls || savingDraft} onClick={handleSaveDraft}>
                {savingDraft ? <><Loader2 size={13} className="awb-spin" /> {t('saving', { defaultValue: 'Saving…' })}</> : t('awb_save_draft_btn', { defaultValue: 'Save as Draft' })}
              </button>
              <button className="wfd-btn-save" disabled={!lastTestResult?.success} onClick={async () => { await autoSaveDraft(); setStep(5); }}>
                {t('awb_continue_btn', { defaultValue: 'Continue' })} <ArrowRight size={13} />
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ── Step 5: Response Mapping (external_api only) ── */}
      {step === 5 && actionType === 'external_api' && (
        <div className="awb-card">
          <WorkflowFieldSuggestions suggestions={missingWorkflowFields} usedBy={missingFieldUsedBy} onCreated={handleFieldCreated} />

          <p className="awb-hint">{t('awb_response_mapping_hint', { defaultValue: 'The AI proposes which parts of the real response are worth capturing — grounded in the actual response and what you originally asked for, not everything the API returns.' })}</p>

          {lastTestResult?.callTrace && lastTestResult.callTrace.length > 0 && (
            <div className="awb-field">
              <label className="awb-label">{t('awb_captured_response_label', { defaultValue: 'Captured response (from the Test step)' })}</label>
              {lastTestResult.callTrace.map((c: any, i: number) => {
                const fullResponse = c.rawResponse || c.rawResult || c.responsePreview || '';
                const expanded = expandedResponseIndex === i;
                return (
                  <div key={i} className="tam-trace-row">
                    <div className="tam-trace-top">
                      <span className="tam-trace-name">{c.name}</span>
                      <span className="tam-trace-status">{String(c.status ?? '')}</span>
                    </div>
                    {fullResponse && (
                      <>
                        <pre className={`tam-trace-resp${expanded ? ' tam-trace-resp--expanded' : ''}`}>{fullResponse}</pre>
                        <button
                          className="wfd-btn-ghost tam-trace-expand-btn"
                          type="button"
                          onClick={() => setExpandedResponseIndex(expanded ? null : i)}
                        >
                          {expanded
                            ? t('test_action_show_less_btn', { defaultValue: 'Show less' })
                            : t('test_action_show_full_response_btn', { defaultValue: 'Show full response' })}
                        </button>
                      </>
                    )}
                  </div>
                );
              })}
            </div>
          )}

          <div className="awb-field">
            <button className="wfd-btn-ghost" type="button" onClick={handleMapResponse} disabled={mappingResponseLoading || !lastTestResult?.callTrace}>
              {mappingResponseLoading
                ? <><Loader2 size={13} className="awb-spin" /> {t('test_action_auto_map_running', { defaultValue: 'Analyzing response…' })}</>
                : <><Sparkles size={13} /> {t('awb_map_response_btn', { defaultValue: 'Map Response with AI' })}</>}
            </button>
            {mappingResponseError && <p className="awb-error">{mappingResponseError}</p>}

            {responseMapProposal && (
              <div className="tam-proposal">
                <div className="tam-sec-lbl">{t('test_action_proposed_changes_heading', { defaultValue: 'PROPOSED MAPPING CHANGES' })}</div>
                {responseMapProposal.calls.map(c => (
                  <div key={c.id} className="tam-proposal-call">
                    {c.responseCaptures.map((cap, i) => (
                      <div key={i} className="tam-field-row">
                        <span className="tam-field-key">{cap.name}</span>
                        <span className="tam-captured-val">{cap.jsonPath ?? cap.resultPath}</span>
                      </div>
                    ))}
                  </div>
                ))}
                {responseMapProposal.fieldMappingsResponse.map((m, i) => (
                  <div key={i} className="tam-field-row">
                    <span className="tam-field-key">{m.captureName}</span>
                    <span className="tam-captured-val">→ {m.target}</span>
                  </div>
                ))}
                <button className="wfd-btn-save tam-apply-btn" onClick={applyResponseMapProposal}>
                  {t('test_action_apply_mapping_btn', { defaultValue: 'Apply to draft' })}
                </button>
              </div>
            )}
          </div>

          <ExternalApiFieldMappingsEditor
            mappings={draftMappings}
            onChange={handleMappingsChange}
            ticketFieldKeys={ticketFieldKeys}
            workflowFieldKeys={workflowFieldKeys}
            captureNames={captureNames}
            showRequest={false}
          />

          {responseMapped && (
            <div className="awb-field">
              <label className="awb-label">{t('awb_verify_captures_label', { defaultValue: 'Verify Captures' })}</label>
              <p className="awb-hint">{t('awb_verify_captures_hint', { defaultValue: 'Re-checks your JSONPaths against the response already captured in the Test step — no new live call is made.' })}</p>
              <button className="wfd-btn-ghost" type="button" onClick={handleVerifyCaptures} disabled={verifyingCaptures}>
                {verifyingCaptures
                  ? <><Loader2 size={13} className="awb-spin" /> {t('awb_verifying_captures_ellipsis', { defaultValue: 'Verifying…' })}</>
                  : <><Play size={13} /> {t('awb_verify_captures_btn', { defaultValue: 'Verify Captures' })}</>}
              </button>
              {verifyCapturesError && <p className="awb-error">{verifyCapturesError}</p>}
              {verifiedCapturedValues && (
                <div className="tam-sec">
                  <div className="tam-sec-lbl">{t('captured_values_label', { defaultValue: 'CAPTURED VALUES' })}</div>
                  {Object.keys(verifiedCapturedValues).length === 0 && (
                    <p className="wfd-hint-xs">{t('awb_verify_captures_empty', { defaultValue: 'Nothing captured — check the JSONPaths above against the response.' })}</p>
                  )}
                  {Object.entries(verifiedCapturedValues).map(([k, v]) => (
                    <div key={k} className="tam-field-row">
                      <span className="tam-field-key">{k}</span>
                      <span className="tam-captured-val">{String(v)}</span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {saveError && <p className="awb-error">{saveError}</p>}

          <div className="awb-actions">
            <button className="wfd-btn-ghost" onClick={() => setStep(4)}><ArrowLeft size={13} /> {t('back_btn', { defaultValue: 'Back' })}</button>
            <div className="awb-actions-group">
              <button className="wfd-btn-ghost" disabled={savingDraft} onClick={handleSaveDraft}>
                {savingDraft ? <><Loader2 size={13} className="awb-spin" /> {t('saving', { defaultValue: 'Saving…' })}</> : t('awb_save_draft_btn', { defaultValue: 'Save as Draft' })}
              </button>
              <button className="wfd-btn-save" disabled={!responseMapped} onClick={async () => { await autoSaveDraft(); setStep(6); }}>
                {t('awb_continue_btn', { defaultValue: 'Continue' })} <ArrowRight size={13} />
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ── Review & Save — MCP's step 4, external_api's step 6 ── */}
      {((step === 4 && actionType === 'mcp_tool') || (step === 6 && actionType === 'external_api')) && (
        <div className="awb-card">
          <div className="awb-field">
            <label className="awb-label">{t('awb_action_item_title_label', { defaultValue: 'Action item title' })}</label>
            <input className="wfd-inp" value={nodeTitle} onChange={e => setNodeTitle(e.target.value)} placeholder={t('awb_action_item_title_placeholder', { defaultValue: 'Order Laptop' }) as string} />
          </div>

          <WorkflowFieldSuggestions suggestions={missingWorkflowFields} usedBy={missingFieldUsedBy} onCreated={handleFieldCreated} />

          {actionType === 'mcp_tool' ? (
            <McpResponseMappingsEditor
              mappings={mcpDraftMappings}
              onChange={setMcpDraftMappings}
              captureNames={mcpCaptureNames}
              ticketFieldKeys={ticketFieldKeys}
              workflowFieldKeys={workflowFieldKeys}
            />
          ) : (
            <ExternalApiFieldMappingsEditor
              mappings={draftMappings}
              onChange={handleMappingsChange}
              ticketFieldKeys={ticketFieldKeys}
              workflowFieldKeys={workflowFieldKeys}
              captureNames={captureNames}
            />
          )}

          <div className="awb-field">
            <label className="awb-label">{t('awb_save_as_label', { defaultValue: 'Save as' })}</label>
            <div className="awb-radio-row">
              <label className="awb-radio">
                <input type="radio" checked={targetMode === 'new'} onChange={() => setTargetMode('new')} />
                {t('awb_new_library_entry_option', { defaultValue: 'New library entry' })}
              </label>
              <label className="awb-radio">
                <input
                  type="radio"
                  checked={targetMode === 'existing'}
                  onChange={() => setTargetMode('existing')}
                  disabled={existingLibraryEntries.length === 0}
                />
                {existingLibraryEntries.length === 0
                  ? t('awb_overwrite_existing_entry_none_option', { defaultValue: 'Overwrite existing {{type}} entry (none yet)', type: actionType })
                  : t('awb_overwrite_existing_entry_option', { defaultValue: 'Overwrite existing {{type}} entry', type: actionType })}
              </label>
            </div>
            {targetMode === 'existing' && (
              <select className="wfd-sel" value={targetNodeId} onChange={e => setTargetNodeId(e.target.value)}>
                <option value="">{t('select_item_placeholder', { defaultValue: '— Select item —' })}</option>
                {existingLibraryEntries.map(entry => <option key={entry.id} value={entry.id}>{entry.name}</option>)}
              </select>
            )}
          </div>

          {saveError && <p className="awb-error">{saveError}</p>}

          <div className="awb-actions">
            <button className="wfd-btn-ghost" onClick={() => setStep(actionType === 'mcp_tool' ? 3 : 5)}><ArrowLeft size={13} /> {t('back_btn', { defaultValue: 'Back' })}</button>
            <div className="awb-actions-group">
              <button className="wfd-btn-ghost" disabled={savingDraft} onClick={handleSaveDraft}>
                {savingDraft ? <><Loader2 size={13} className="awb-spin" /> {t('saving', { defaultValue: 'Saving…' })}</> : t('awb_save_draft_btn', { defaultValue: 'Save as Draft' })}
              </button>
              <button
                className="wfd-btn-save"
                disabled={saving || (targetMode === 'existing' && !targetNodeId)}
                onClick={handleSave}
              >
                {saving ? <><Loader2 size={13} className="awb-spin" /> {t('saving', { defaultValue: 'Saving…' })}</> : <>{t('awb_save_complete_btn', { defaultValue: 'Save & Complete' })} <Check size={13} /></>}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
